force_cast: warning
force_try: warning
disabled_rules:
  - colon
  - comma
  - control_statement
  - trailing_whitespace
excluded:
    - Pods
    - ../Pods
    - ./Pods
    - /Pods
    - Project/R.generated.swift
    - Project/Pods

line_length:
  warning: 120
  error: 500

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 40
  error: 120

opt_in_rules:
  - empty_count
  - force_unwrapping
  - legacy_constant
  - legacy_constructor
  - private_action
  - private_outlet
